### ISSUE TITLE
Reintroduce `npm config set unsafe-perm true` line in Dockerfile?

### ISSUE THREAD

**Issue by mturley** [kubev2v/forklift-ui#872]
See https://github.com/konveyor/forklift-ui/pull/871#discussion_r774157618. As part of that PR, this line was removed from the dockerfile:

```
RUN npm config set unsafe-perm true && npm run install:ws && npm run build
```

@gildub can we chat about this line when we're both back from break? Is it necessary only for the API rewrite to TypeScript, or for the npm workspaces refactor to work at all?

**Comment by gildub** [comment]
@mturley 
A couple of changes to Dockerfile happened after we moved to nodejs-16 and then npm workspaces.
This is one of them, the other being `USER root` in the builder (first block) section.

I had a different behavior between local and remote builds, which we now know are related to cachito not supporting npm workspaces.
So now that ubi8/nodejs-16 (since 21st Dec.) is based on LTS and once Cachito is up to speed let's recheck and revisit accordingly.

**Comment by yaacov** [comment]
closing as new development is moving to:
https://github.com/kubev2v/forklift-console-plugin
